### ISSUE TITLE
the cuda machine you used and the training time?

### ISSUE THREAD

**Issue by bright1993ff66** [HuangLianzhe/TextLevelGCN#1]
Hi Lianzhe,

I am very interested in your paper. But what cuda machine did you use to train your model? How long does it take to train one epoch?

**Comment by mojave-pku** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    GTX 1080Ti，I can't remember the specific time of each epoch, but the model can usually get the best results in 1-2 hours when running on the r8 and r52 datasets.

    On 12/9/2019 14:37，Bright Chang<notifications@github.com> wrote： 


Hi Lianzhe,
I am very interested in your paper. But what cuda machine did you use to train your model? How long does it take to train one epoch?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.


        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }

**Comment by bright1993ff66** [comment]
@HuangLianzhe Thank you for your prompt reply!
