### ISSUE TITLE
the word2vec module in the model.py?

### ISSUE THREAD

**Issue by bright1993ff66** [HuangLianzhe/TextLevelGCN#2]
In the [model.py](https://github.com/HuangLianzhe/TextLevelGCN/blob/master/model.py), the module word2vec is not defined. Are you using the word2vec from [gensim](https://radimrehurek.com/gensim/models/word2vec.html)? such as:

```Python
from gensim.models import Word2Vec
```

**Comment by mojave-pku** [comment]
No, you can install the package with the name 'word2vec' by pip.
`pip3 install word2vec`

**Comment by bright1993ff66** [comment]
@HuangLianzhe I will try that! Thanks~
