### ISSUE TITLE
read data randomly

### ISSUE THREAD

**Issue by zgyangleo** [HuangLianzhe/TextLevelGCN#3]
i noticed that the way you read the data is sequential, the results is bad when i change the data order randomly. is there any reason?

**Comment by mojave-pku** [comment]
We have not done similar experiments and don't know much about the reason for this phenomenon. Theoretically changing the order of reading data should not affect the experimental results.

**Comment by zgyangleo** [comment]
Hi,  i want to use 2gpu to train the model,  how to seperate the batchsize into two, just like bachsize 32, one gpu is 16, another is 16? please give me some idea. thank you

**Comment by mojave-pku** [comment]
Regarding this question, I suggest you search the Internet for answers. This problem is not much related to our model.
